server:
  port: 8081
spring:
  application:
    name: shyx
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shyx?useSSL=false&serverTimezone=UTC
    username: root
    password: Wang2931
  redis:
    host: 192.168.44.99
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-active: 10 # 最大连接数
        max-idle: 10 # 最大空闲连接数
        min-idle: 1 # 最小空闲连接数
        time-between-eviction-runs: 10s # 连接回收周期
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.shyx.entity # 别名扫描包
logging:
  level:
    com.shyx: debug